### ISSUE TITLE
loki can not start

### ISSUE THREAD

**Issue by EtanYu** [grafana/tutorial-environment#1]
I just clone the tutorial and start it.but loki can not start.

➜  tutorial-environment git:(master) docker-compose ps
              Name                             Command               State            Ports
----------------------------------------------------------------------------------------------------
tutorial-environment_app_1          /bin/sh -c /app http://db  ...   Up       0.0.0.0:8081->80/tcp
tutorial-environment_db_1           /db                              Up       0.0.0.0:8082->80/tcp
tutorial-environment_grafana_1      /run.sh                          Up       0.0.0.0:3000->3000/tcp
tutorial-environment_loki_1         /usr/bin/loki -config.file ...   Exit 1
tutorial-environment_prometheus_1   /bin/prometheus --config.f ...   Up       0.0.0.0:9090->9090/tcp
tutorial-environment_promtail_1     /usr/bin/promtail -config. ...   Up

so I pull latest grafana/loki again and restart,still the same.

docker-compose logs give me this hint:
loki_1        | failed parsing config: /etc/loki/local-config.yaml: not a valid duration string: "0"

can someone check the config yaml?

**Comment by marcusolsson** [comment]
Thanks for reporting this! Seems like the latest image of Loki fails to run. I've updated the docker-compose file to use a fixed version of Loki rather than the latest. Should work now if you update the images by pulling the latest changes. Let me know if that works for you.

**Comment by EtanYu** [comment]
great,It works.Thx
