### ISSUE TITLE
Get error ‘Connection reset by peer ’ when access by host？

### ISSUE THREAD

**Issue by Windeal** [grafana/tutorial-environment#2]
I set up the application follow the tutorial [https://grafana.com/tutorials/grafana-fundamentals/#2](https://grafana.com/tutorials/grafana-fundamentals/#2)
All services are up-and-running:
![image](https://user-images.githubusercontent.com/8803957/91440656-80698880-e8a1-11ea-8fe7-16c10ba3c2ca.png)

But when I try  to access the sample application in host,  I get error 'Connection reset by peer', 
![image](https://user-images.githubusercontent.com/8803957/91441150-4947a700-e8a2-11ea-910f-a76fae7a1a64.png)

**Comment by marcusolsson** [comment]
Unfortunately, I'm not able to reproduce this, and `Connection reset by peer` is a rather generic error.

Could you add `curl --trace-ascii dump.txt http://127.0.0.1:3000` and post the contents of `dump.txt`?
