### ISSUE TITLE
Small inconsistencies with tutorial steps

### ISSUE THREAD

**Issue by mthorning** [grafana/tutorial-environment#26]
I spotted a couple of inconsistencies whilst completing the "Grafana fundamentals" and the "Get started with Grafana Alerting" tutorials which caused me some confusion that would be good to address if possible.

* [This video](https://grafana.com/tutorials/grafana-fundamentals/#display-grafana-managed-alert-rules-to-your-dashboard) shows some options when setting up an alert rule which are only visible if you first check "Advanced options". I don't know if it's possible to control whether this option is checked on page load via configuration or not but mentioning it just-in-case.

* The `Alerts & IRM` menu item is referenced in [the part 2 tutorial](https://grafana.com/tutorials/alerting-get-started-pt2/#create-notification-policies) but is not available in my instance of Grafana. This is an inconsistency with the cloud instance so hopefully there's a config option to turn on IRM here.

**Comment by tonypowa** [comment]
TODO:

- [ ] replace requestbin with webhook.site
- [ ] alert rule configuration: use advanced instructions so UI matches the options that can be seen in the video
- [ ]  Alerts & IRM menu item (keep it / replace it with `Alerting`) CC @brendamuir
