### ISSUE TITLE
ERROR Service Unavailable

### ISSUE THREAD

**Issue by gamusta** [grafana/tutorial-environment#3]
This error occurs after **docker-compose up -d**
ERROR: Get https://registry-1.docker.io/v2/prom/prometheus/manifests/sha256:efd99a6be65885c07c559679a0df4ec709604bcdd8cd83f0d00a1a683b28fb6a: Service Unavailable

**Comment by gamusta** [comment]
Corrected using 
```
prometheus:
    image: prom/prometheus:v2.21.0
```

**Comment by marcusolsson** [comment]
Thanks for reporting this! I've bumped the versions. Could you run `git pull` on the `tutorials-environment` repository and try again to see if it works for you?
